//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BMS2015Entities : DbContext
    {
        public BMS2015Entities()
            : base("name=BMS2015Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<proveedore> proveedores { get; set; }
        public virtual DbSet<razones_devoluciones_clientes> razones_devoluciones_clientes { get; set; }
        public virtual DbSet<establecimiento> establecimientos { get; set; }
        public virtual DbSet<inventario_localizacion> inventario_localizacion { get; set; }
        public virtual DbSet<razones_no_disponible> razones_no_disponible { get; set; }
        public virtual DbSet<localizacione> localizaciones { get; set; }
        public virtual DbSet<solicitudes_surtido_pick_slot> solicitudes_surtido_pick_slot { get; set; }
    
        public virtual ObjectResult<MobileBMS_Login_Result> MobileBMS_Login(string usuario, string clave)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileBMS_Login_Result>("MobileBMS_Login", usuarioParameter, claveParameter);
        }
    
        public virtual ObjectResult<MobileBMS_EstabsUsuario_Result> MobileBMS_EstabsUsuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileBMS_EstabsUsuario_Result>("MobileBMS_EstabsUsuario", usuarioParameter);
        }
    
        public virtual ObjectResult<MobileBMS_DetalleConteo_Result> MobileBMS_DetalleConteo(string folio)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileBMS_DetalleConteo_Result>("MobileBMS_DetalleConteo", folioParameter);
        }
    
        public virtual ObjectResult<MobileBMS_InfoConteo_Result> MobileBMS_InfoConteo(string folio)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileBMS_InfoConteo_Result>("MobileBMS_InfoConteo", folioParameter);
        }
    
        public virtual int MobileBMS_GuardarConteo(string folio, string codProd, Nullable<System.DateTime> fecha, string usuario, Nullable<decimal> uC, Nullable<decimal> uA, Nullable<decimal> existUC, Nullable<decimal> existUA, string programacion, string notas, Nullable<bool> contado)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var codProdParameter = codProd != null ?
                new ObjectParameter("CodProd", codProd) :
                new ObjectParameter("CodProd", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var uCParameter = uC.HasValue ?
                new ObjectParameter("UC", uC) :
                new ObjectParameter("UC", typeof(decimal));
    
            var uAParameter = uA.HasValue ?
                new ObjectParameter("UA", uA) :
                new ObjectParameter("UA", typeof(decimal));
    
            var existUCParameter = existUC.HasValue ?
                new ObjectParameter("existUC", existUC) :
                new ObjectParameter("existUC", typeof(decimal));
    
            var existUAParameter = existUA.HasValue ?
                new ObjectParameter("existUA", existUA) :
                new ObjectParameter("existUA", typeof(decimal));
    
            var programacionParameter = programacion != null ?
                new ObjectParameter("Programacion", programacion) :
                new ObjectParameter("Programacion", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var contadoParameter = contado.HasValue ?
                new ObjectParameter("Contado", contado) :
                new ObjectParameter("Contado", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MobileBMS_GuardarConteo", folioParameter, codProdParameter, fechaParameter, usuarioParameter, uCParameter, uAParameter, existUCParameter, existUAParameter, programacionParameter, notasParameter, contadoParameter);
        }
    
        public virtual ObjectResult<MobileBMS_BuscarProductos_Result> MobileBMS_BuscarProductos(string codigo, string filtro, string estab)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var filtroParameter = filtro != null ?
                new ObjectParameter("Filtro", filtro) :
                new ObjectParameter("Filtro", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("Estab", estab) :
                new ObjectParameter("Estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileBMS_BuscarProductos_Result>("MobileBMS_BuscarProductos", codigoParameter, filtroParameter, estabParameter);
        }
    
        public virtual ObjectResult<string> MobileWS_CheckEscanerProd(string codigoBarras, string estab)
        {
            var codigoBarrasParameter = codigoBarras != null ?
                new ObjectParameter("CodigoBarras", codigoBarras) :
                new ObjectParameter("CodigoBarras", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("Estab", estab) :
                new ObjectParameter("Estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MobileWS_CheckEscanerProd", codigoBarrasParameter, estabParameter);
        }
    
        public virtual int MobileBMS_GuardarNotasConteoProd(string folio, string codProd, string notas)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var codProdParameter = codProd != null ?
                new ObjectParameter("CodProd", codProd) :
                new ObjectParameter("CodProd", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MobileBMS_GuardarNotasConteoProd", folioParameter, codProdParameter, notasParameter);
        }
    
        public virtual ObjectResult<MobileBMS_InventarioProductoFecha_Result> MobileBMS_InventarioProductoFecha(string producto, string estab, Nullable<System.DateTime> fecha)
        {
            var productoParameter = producto != null ?
                new ObjectParameter("producto", producto) :
                new ObjectParameter("producto", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("estab", estab) :
                new ObjectParameter("estab", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MobileBMS_InventarioProductoFecha_Result>("MobileBMS_InventarioProductoFecha", productoParameter, estabParameter, fechaParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_OrdenCompra_Result> CalkinsWS_OrdenCompra(string folio, string transaccion, string estab, string usuario)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("transaccion", transaccion) :
                new ObjectParameter("transaccion", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("estab", estab) :
                new ObjectParameter("estab", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_OrdenCompra_Result>("CalkinsWS_OrdenCompra", folioParameter, transaccionParameter, estabParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_OrdenCompraDetalle_Result> CalkinsWS_OrdenCompraDetalle(string folio, string transaccion, string estab, string usuario)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("transaccion", transaccion) :
                new ObjectParameter("transaccion", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("estab", estab) :
                new ObjectParameter("estab", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_OrdenCompraDetalle_Result>("CalkinsWS_OrdenCompraDetalle", folioParameter, transaccionParameter, estabParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_ProductoEntrada_Result> CalkinsWS_ProductoEntrada(string cod_prv, string cod_estab, string cod_prod)
        {
            var cod_prvParameter = cod_prv != null ?
                new ObjectParameter("cod_prv", cod_prv) :
                new ObjectParameter("cod_prv", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_ProductoEntrada_Result>("CalkinsWS_ProductoEntrada", cod_prvParameter, cod_estabParameter, cod_prodParameter);
        }
    
        public virtual ObjectResult<string> CalkinsWS_ValidarProdEntrada(string prod, string estab, string oC, Nullable<System.DateTime> caducidad, Nullable<bool> esLote, Nullable<decimal> cant, string unid)
        {
            var prodParameter = prod != null ?
                new ObjectParameter("Prod", prod) :
                new ObjectParameter("Prod", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("Estab", estab) :
                new ObjectParameter("Estab", typeof(string));
    
            var oCParameter = oC != null ?
                new ObjectParameter("OC", oC) :
                new ObjectParameter("OC", typeof(string));
    
            var caducidadParameter = caducidad.HasValue ?
                new ObjectParameter("Caducidad", caducidad) :
                new ObjectParameter("Caducidad", typeof(System.DateTime));
    
            var esLoteParameter = esLote.HasValue ?
                new ObjectParameter("EsLote", esLote) :
                new ObjectParameter("EsLote", typeof(bool));
    
            var cantParameter = cant.HasValue ?
                new ObjectParameter("Cant", cant) :
                new ObjectParameter("Cant", typeof(decimal));
    
            var unidParameter = unid != null ?
                new ObjectParameter("Unid", unid) :
                new ObjectParameter("Unid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CalkinsWS_ValidarProdEntrada", prodParameter, estabParameter, oCParameter, caducidadParameter, esLoteParameter, cantParameter, unidParameter);
        }
    
        public virtual int CalkinsWS_GenerarFolio(string transaccion, string estabCode, Nullable<bool> actualizar, ObjectParameter folio, ObjectParameter maxReng, string equipCode, ObjectParameter unidadPermitida)
        {
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("Transaccion", transaccion) :
                new ObjectParameter("Transaccion", typeof(string));
    
            var estabCodeParameter = estabCode != null ?
                new ObjectParameter("EstabCode", estabCode) :
                new ObjectParameter("EstabCode", typeof(string));
    
            var actualizarParameter = actualizar.HasValue ?
                new ObjectParameter("Actualizar", actualizar) :
                new ObjectParameter("Actualizar", typeof(bool));
    
            var equipCodeParameter = equipCode != null ?
                new ObjectParameter("EquipCode", equipCode) :
                new ObjectParameter("EquipCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GenerarFolio", transaccionParameter, estabCodeParameter, actualizarParameter, folio, maxReng, equipCodeParameter, unidadPermitida);
        }
    
        public virtual int CalkinsWS_GuardarDetalleEntrada(string folio, string oC, Nullable<int> id, string cod_prod, Nullable<decimal> cantidad, string unidad, Nullable<bool> pallet, Nullable<System.DateTime> caducidad, string lote_fab, string notas, Nullable<long> id_origen, string cod_estab, string prv, ObjectParameter msg)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var oCParameter = oC != null ?
                new ObjectParameter("OC", oC) :
                new ObjectParameter("OC", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(decimal));
    
            var unidadParameter = unidad != null ?
                new ObjectParameter("unidad", unidad) :
                new ObjectParameter("unidad", typeof(string));
    
            var palletParameter = pallet.HasValue ?
                new ObjectParameter("pallet", pallet) :
                new ObjectParameter("pallet", typeof(bool));
    
            var caducidadParameter = caducidad.HasValue ?
                new ObjectParameter("caducidad", caducidad) :
                new ObjectParameter("caducidad", typeof(System.DateTime));
    
            var lote_fabParameter = lote_fab != null ?
                new ObjectParameter("lote_fab", lote_fab) :
                new ObjectParameter("lote_fab", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("notas", notas) :
                new ObjectParameter("notas", typeof(string));
    
            var id_origenParameter = id_origen.HasValue ?
                new ObjectParameter("id_origen", id_origen) :
                new ObjectParameter("id_origen", typeof(long));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var prvParameter = prv != null ?
                new ObjectParameter("prv", prv) :
                new ObjectParameter("prv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GuardarDetalleEntrada", folioParameter, oCParameter, idParameter, cod_prodParameter, cantidadParameter, unidadParameter, palletParameter, caducidadParameter, lote_fabParameter, notasParameter, id_origenParameter, cod_estabParameter, prvParameter, msg);
        }
    
        public virtual int CalkinsWS_GuardarEntrada(string folio, string usuario, string estab, string notas, string oC, string prv)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("Estab", estab) :
                new ObjectParameter("Estab", typeof(string));
    
            var notasParameter = notas != null ?
                new ObjectParameter("Notas", notas) :
                new ObjectParameter("Notas", typeof(string));
    
            var oCParameter = oC != null ?
                new ObjectParameter("OC", oC) :
                new ObjectParameter("OC", typeof(string));
    
            var prvParameter = prv != null ?
                new ObjectParameter("Prv", prv) :
                new ObjectParameter("Prv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GuardarEntrada", folioParameter, usuarioParameter, estabParameter, notasParameter, oCParameter, prvParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_DetalleRecepcionTransferencia_Result> CalkinsWS_DetalleRecepcionTransferencia(string folio)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_DetalleRecepcionTransferencia_Result>("CalkinsWS_DetalleRecepcionTransferencia", folioParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_InfoTransferencia_Result> CalkinsWS_InfoTransferencia(string folio)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_InfoTransferencia_Result>("CalkinsWS_InfoTransferencia", folioParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_ProductosSurtidos_Result> CalkinsWS_ProductosSurtidos(string folio)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_ProductosSurtidos_Result>("CalkinsWS_ProductosSurtidos", folioParameter);
        }
    
        public virtual int CalkinsWS_GuadarRecepcionTransferencia(string folio, string transaccion, string transaccion_origen, string cod_estab, string cod_estab_alterno, string folio_transferencia, Nullable<decimal> importeGeneral, Nullable<decimal> ivaGeneral, Nullable<decimal> iepsGeneral, Nullable<decimal> costoGeneral, Nullable<decimal> unidadesGeneral, Nullable<decimal> piezasGeneral, Nullable<decimal> pesoGeneral, Nullable<decimal> volumenGeneral, string usuario, string razon_aod_inventario, string folio_referencia, Nullable<short> orden_embarque, Nullable<bool> recoge_mercancia, string notasGeneral, string clave_afectacion_inventario, string operacion)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("transaccion", transaccion) :
                new ObjectParameter("transaccion", typeof(string));
    
            var transaccion_origenParameter = transaccion_origen != null ?
                new ObjectParameter("transaccion_origen", transaccion_origen) :
                new ObjectParameter("transaccion_origen", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var cod_estab_alternoParameter = cod_estab_alterno != null ?
                new ObjectParameter("cod_estab_alterno", cod_estab_alterno) :
                new ObjectParameter("cod_estab_alterno", typeof(string));
    
            var folio_transferenciaParameter = folio_transferencia != null ?
                new ObjectParameter("folio_transferencia", folio_transferencia) :
                new ObjectParameter("folio_transferencia", typeof(string));
    
            var importeGeneralParameter = importeGeneral.HasValue ?
                new ObjectParameter("importeGeneral", importeGeneral) :
                new ObjectParameter("importeGeneral", typeof(decimal));
    
            var ivaGeneralParameter = ivaGeneral.HasValue ?
                new ObjectParameter("ivaGeneral", ivaGeneral) :
                new ObjectParameter("ivaGeneral", typeof(decimal));
    
            var iepsGeneralParameter = iepsGeneral.HasValue ?
                new ObjectParameter("iepsGeneral", iepsGeneral) :
                new ObjectParameter("iepsGeneral", typeof(decimal));
    
            var costoGeneralParameter = costoGeneral.HasValue ?
                new ObjectParameter("costoGeneral", costoGeneral) :
                new ObjectParameter("costoGeneral", typeof(decimal));
    
            var unidadesGeneralParameter = unidadesGeneral.HasValue ?
                new ObjectParameter("unidadesGeneral", unidadesGeneral) :
                new ObjectParameter("unidadesGeneral", typeof(decimal));
    
            var piezasGeneralParameter = piezasGeneral.HasValue ?
                new ObjectParameter("piezasGeneral", piezasGeneral) :
                new ObjectParameter("piezasGeneral", typeof(decimal));
    
            var pesoGeneralParameter = pesoGeneral.HasValue ?
                new ObjectParameter("pesoGeneral", pesoGeneral) :
                new ObjectParameter("pesoGeneral", typeof(decimal));
    
            var volumenGeneralParameter = volumenGeneral.HasValue ?
                new ObjectParameter("volumenGeneral", volumenGeneral) :
                new ObjectParameter("volumenGeneral", typeof(decimal));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var razon_aod_inventarioParameter = razon_aod_inventario != null ?
                new ObjectParameter("razon_aod_inventario", razon_aod_inventario) :
                new ObjectParameter("razon_aod_inventario", typeof(string));
    
            var folio_referenciaParameter = folio_referencia != null ?
                new ObjectParameter("folio_referencia", folio_referencia) :
                new ObjectParameter("folio_referencia", typeof(string));
    
            var orden_embarqueParameter = orden_embarque.HasValue ?
                new ObjectParameter("orden_embarque", orden_embarque) :
                new ObjectParameter("orden_embarque", typeof(short));
    
            var recoge_mercanciaParameter = recoge_mercancia.HasValue ?
                new ObjectParameter("recoge_mercancia", recoge_mercancia) :
                new ObjectParameter("recoge_mercancia", typeof(bool));
    
            var notasGeneralParameter = notasGeneral != null ?
                new ObjectParameter("notasGeneral", notasGeneral) :
                new ObjectParameter("notasGeneral", typeof(string));
    
            var clave_afectacion_inventarioParameter = clave_afectacion_inventario != null ?
                new ObjectParameter("clave_afectacion_inventario", clave_afectacion_inventario) :
                new ObjectParameter("clave_afectacion_inventario", typeof(string));
    
            var operacionParameter = operacion != null ?
                new ObjectParameter("Operacion", operacion) :
                new ObjectParameter("Operacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GuadarRecepcionTransferencia", folioParameter, transaccionParameter, transaccion_origenParameter, cod_estabParameter, cod_estab_alternoParameter, folio_transferenciaParameter, importeGeneralParameter, ivaGeneralParameter, iepsGeneralParameter, costoGeneralParameter, unidadesGeneralParameter, piezasGeneralParameter, pesoGeneralParameter, volumenGeneralParameter, usuarioParameter, razon_aod_inventarioParameter, folio_referenciaParameter, orden_embarqueParameter, recoge_mercanciaParameter, notasGeneralParameter, clave_afectacion_inventarioParameter, operacionParameter);
        }
    
        public virtual int CalkinsWS_GuardarDetalleRecepcion(string cod_prod, string unid, string cod_estab, string folioTransferencia, string transaccion, Nullable<bool> backorder, Nullable<bool> afecta_no_disponible, ObjectParameter cant, Nullable<decimal> costo_operativo_unitario, ObjectParameter costo_promedio, string cod_prv, Nullable<decimal> cantidad_adicional, string unidad, Nullable<decimal> cantidad, Nullable<decimal> precio_lista, string tipo_precio_venta, Nullable<decimal> importe, Nullable<decimal> iva, Nullable<decimal> ieps, Nullable<decimal> costo, Nullable<decimal> peso, Nullable<decimal> volumen, Nullable<int> id_origen, string abreviatura_unidad, Nullable<System.DateTime> fecha_cad, string lote_fabricacion, Nullable<int> pallets, Nullable<bool> agregar_lote, ObjectParameter msg)
        {
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var unidParameter = unid != null ?
                new ObjectParameter("unid", unid) :
                new ObjectParameter("unid", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var folioTransferenciaParameter = folioTransferencia != null ?
                new ObjectParameter("folioTransferencia", folioTransferencia) :
                new ObjectParameter("folioTransferencia", typeof(string));
    
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("transaccion", transaccion) :
                new ObjectParameter("transaccion", typeof(string));
    
            var backorderParameter = backorder.HasValue ?
                new ObjectParameter("backorder", backorder) :
                new ObjectParameter("backorder", typeof(bool));
    
            var afecta_no_disponibleParameter = afecta_no_disponible.HasValue ?
                new ObjectParameter("afecta_no_disponible", afecta_no_disponible) :
                new ObjectParameter("afecta_no_disponible", typeof(bool));
    
            var costo_operativo_unitarioParameter = costo_operativo_unitario.HasValue ?
                new ObjectParameter("costo_operativo_unitario", costo_operativo_unitario) :
                new ObjectParameter("costo_operativo_unitario", typeof(decimal));
    
            var cod_prvParameter = cod_prv != null ?
                new ObjectParameter("cod_prv", cod_prv) :
                new ObjectParameter("cod_prv", typeof(string));
    
            var cantidad_adicionalParameter = cantidad_adicional.HasValue ?
                new ObjectParameter("Cantidad_adicional", cantidad_adicional) :
                new ObjectParameter("Cantidad_adicional", typeof(decimal));
    
            var unidadParameter = unidad != null ?
                new ObjectParameter("unidad", unidad) :
                new ObjectParameter("unidad", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(decimal));
    
            var precio_listaParameter = precio_lista.HasValue ?
                new ObjectParameter("precio_lista", precio_lista) :
                new ObjectParameter("precio_lista", typeof(decimal));
    
            var tipo_precio_ventaParameter = tipo_precio_venta != null ?
                new ObjectParameter("tipo_precio_venta", tipo_precio_venta) :
                new ObjectParameter("tipo_precio_venta", typeof(string));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("importe", importe) :
                new ObjectParameter("importe", typeof(decimal));
    
            var ivaParameter = iva.HasValue ?
                new ObjectParameter("iva", iva) :
                new ObjectParameter("iva", typeof(decimal));
    
            var iepsParameter = ieps.HasValue ?
                new ObjectParameter("ieps", ieps) :
                new ObjectParameter("ieps", typeof(decimal));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("costo", costo) :
                new ObjectParameter("costo", typeof(decimal));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(decimal));
    
            var volumenParameter = volumen.HasValue ?
                new ObjectParameter("volumen", volumen) :
                new ObjectParameter("volumen", typeof(decimal));
    
            var id_origenParameter = id_origen.HasValue ?
                new ObjectParameter("id_origen", id_origen) :
                new ObjectParameter("id_origen", typeof(int));
    
            var abreviatura_unidadParameter = abreviatura_unidad != null ?
                new ObjectParameter("abreviatura_unidad", abreviatura_unidad) :
                new ObjectParameter("abreviatura_unidad", typeof(string));
    
            var fecha_cadParameter = fecha_cad.HasValue ?
                new ObjectParameter("fecha_cad", fecha_cad) :
                new ObjectParameter("fecha_cad", typeof(System.DateTime));
    
            var lote_fabricacionParameter = lote_fabricacion != null ?
                new ObjectParameter("lote_fabricacion", lote_fabricacion) :
                new ObjectParameter("lote_fabricacion", typeof(string));
    
            var palletsParameter = pallets.HasValue ?
                new ObjectParameter("pallets", pallets) :
                new ObjectParameter("pallets", typeof(int));
    
            var agregar_loteParameter = agregar_lote.HasValue ?
                new ObjectParameter("agregar_lote", agregar_lote) :
                new ObjectParameter("agregar_lote", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GuardarDetalleRecepcion", cod_prodParameter, unidParameter, cod_estabParameter, folioTransferenciaParameter, transaccionParameter, backorderParameter, afecta_no_disponibleParameter, cant, costo_operativo_unitarioParameter, costo_promedio, cod_prvParameter, cantidad_adicionalParameter, unidadParameter, cantidadParameter, precio_listaParameter, tipo_precio_ventaParameter, importeParameter, ivaParameter, iepsParameter, costoParameter, pesoParameter, volumenParameter, id_origenParameter, abreviatura_unidadParameter, fecha_cadParameter, lote_fabricacionParameter, palletsParameter, agregar_loteParameter, msg);
        }
    
        public virtual ObjectResult<CalkinsWS_DetalleEntradaDevolucion_Result> CalkinsWS_DetalleEntradaDevolucion(string folio, string trans)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("Trans", trans) :
                new ObjectParameter("Trans", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_DetalleEntradaDevolucion_Result>("CalkinsWS_DetalleEntradaDevolucion", folioParameter, transParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_EntradaDEvolucion_Result> CalkinsWS_EntradaDEvolucion(string folio, string trans)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("Trans", trans) :
                new ObjectParameter("Trans", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_EntradaDEvolucion_Result>("CalkinsWS_EntradaDEvolucion", folioParameter, transParameter);
        }
    
        public virtual int CalkinsWS_GuardarDetalleEntradaDevolucion(string cod_prod, string unid, string cod_estab, string folioTransferencia, string transaccion, Nullable<bool> backorder, Nullable<bool> afecta_no_disponible, ObjectParameter cant, Nullable<decimal> costo_operativo_unitario, ObjectParameter costo_promedio, string cod_prv, Nullable<decimal> cantidad_adicional, string unidad, Nullable<decimal> cantidad, Nullable<decimal> precio_lista, string tipo_precio_venta, Nullable<decimal> importe, Nullable<decimal> iva, Nullable<decimal> ieps, Nullable<decimal> costo, Nullable<decimal> peso, Nullable<decimal> volumen, Nullable<int> id_origen, string abreviatura_unidad, Nullable<System.DateTime> fecha_cad, string lote_fabricacion, Nullable<int> pallets, Nullable<bool> agregar_lote, ObjectParameter msg)
        {
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var unidParameter = unid != null ?
                new ObjectParameter("unid", unid) :
                new ObjectParameter("unid", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var folioTransferenciaParameter = folioTransferencia != null ?
                new ObjectParameter("folioTransferencia", folioTransferencia) :
                new ObjectParameter("folioTransferencia", typeof(string));
    
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("transaccion", transaccion) :
                new ObjectParameter("transaccion", typeof(string));
    
            var backorderParameter = backorder.HasValue ?
                new ObjectParameter("backorder", backorder) :
                new ObjectParameter("backorder", typeof(bool));
    
            var afecta_no_disponibleParameter = afecta_no_disponible.HasValue ?
                new ObjectParameter("afecta_no_disponible", afecta_no_disponible) :
                new ObjectParameter("afecta_no_disponible", typeof(bool));
    
            var costo_operativo_unitarioParameter = costo_operativo_unitario.HasValue ?
                new ObjectParameter("costo_operativo_unitario", costo_operativo_unitario) :
                new ObjectParameter("costo_operativo_unitario", typeof(decimal));
    
            var cod_prvParameter = cod_prv != null ?
                new ObjectParameter("cod_prv", cod_prv) :
                new ObjectParameter("cod_prv", typeof(string));
    
            var cantidad_adicionalParameter = cantidad_adicional.HasValue ?
                new ObjectParameter("Cantidad_adicional", cantidad_adicional) :
                new ObjectParameter("Cantidad_adicional", typeof(decimal));
    
            var unidadParameter = unidad != null ?
                new ObjectParameter("unidad", unidad) :
                new ObjectParameter("unidad", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(decimal));
    
            var precio_listaParameter = precio_lista.HasValue ?
                new ObjectParameter("precio_lista", precio_lista) :
                new ObjectParameter("precio_lista", typeof(decimal));
    
            var tipo_precio_ventaParameter = tipo_precio_venta != null ?
                new ObjectParameter("tipo_precio_venta", tipo_precio_venta) :
                new ObjectParameter("tipo_precio_venta", typeof(string));
    
            var importeParameter = importe.HasValue ?
                new ObjectParameter("importe", importe) :
                new ObjectParameter("importe", typeof(decimal));
    
            var ivaParameter = iva.HasValue ?
                new ObjectParameter("iva", iva) :
                new ObjectParameter("iva", typeof(decimal));
    
            var iepsParameter = ieps.HasValue ?
                new ObjectParameter("ieps", ieps) :
                new ObjectParameter("ieps", typeof(decimal));
    
            var costoParameter = costo.HasValue ?
                new ObjectParameter("costo", costo) :
                new ObjectParameter("costo", typeof(decimal));
    
            var pesoParameter = peso.HasValue ?
                new ObjectParameter("peso", peso) :
                new ObjectParameter("peso", typeof(decimal));
    
            var volumenParameter = volumen.HasValue ?
                new ObjectParameter("volumen", volumen) :
                new ObjectParameter("volumen", typeof(decimal));
    
            var id_origenParameter = id_origen.HasValue ?
                new ObjectParameter("id_origen", id_origen) :
                new ObjectParameter("id_origen", typeof(int));
    
            var abreviatura_unidadParameter = abreviatura_unidad != null ?
                new ObjectParameter("abreviatura_unidad", abreviatura_unidad) :
                new ObjectParameter("abreviatura_unidad", typeof(string));
    
            var fecha_cadParameter = fecha_cad.HasValue ?
                new ObjectParameter("fecha_cad", fecha_cad) :
                new ObjectParameter("fecha_cad", typeof(System.DateTime));
    
            var lote_fabricacionParameter = lote_fabricacion != null ?
                new ObjectParameter("lote_fabricacion", lote_fabricacion) :
                new ObjectParameter("lote_fabricacion", typeof(string));
    
            var palletsParameter = pallets.HasValue ?
                new ObjectParameter("pallets", pallets) :
                new ObjectParameter("pallets", typeof(int));
    
            var agregar_loteParameter = agregar_lote.HasValue ?
                new ObjectParameter("agregar_lote", agregar_lote) :
                new ObjectParameter("agregar_lote", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GuardarDetalleEntradaDevolucion", cod_prodParameter, unidParameter, cod_estabParameter, folioTransferenciaParameter, transaccionParameter, backorderParameter, afecta_no_disponibleParameter, cant, costo_operativo_unitarioParameter, costo_promedio, cod_prvParameter, cantidad_adicionalParameter, unidadParameter, cantidadParameter, precio_listaParameter, tipo_precio_ventaParameter, importeParameter, ivaParameter, iepsParameter, costoParameter, pesoParameter, volumenParameter, id_origenParameter, abreviatura_unidadParameter, fecha_cadParameter, lote_fabricacionParameter, palletsParameter, agregar_loteParameter, msg);
        }
    
        public virtual int CalkinsWS_GuardarEntradaDevolucion(string folio, string transaccion, string transaccion_origen, string cod_estab, string cod_estab_alterno, string folio_transferencia, Nullable<decimal> importeGeneral, Nullable<decimal> ivaGeneral, Nullable<decimal> iepsGeneral, Nullable<decimal> costoGeneral, Nullable<decimal> unidadesGeneral, Nullable<decimal> piezasGeneral, Nullable<decimal> pesoGeneral, Nullable<decimal> volumenGeneral, string usuario, string razon_aod_inventario, string folio_referencia, Nullable<short> orden_embarque, Nullable<bool> recoge_mercancia, string notasGeneral, string clave_afectacion_inventario, string operacion, string cod_cte)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("transaccion", transaccion) :
                new ObjectParameter("transaccion", typeof(string));
    
            var transaccion_origenParameter = transaccion_origen != null ?
                new ObjectParameter("transaccion_origen", transaccion_origen) :
                new ObjectParameter("transaccion_origen", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var cod_estab_alternoParameter = cod_estab_alterno != null ?
                new ObjectParameter("cod_estab_alterno", cod_estab_alterno) :
                new ObjectParameter("cod_estab_alterno", typeof(string));
    
            var folio_transferenciaParameter = folio_transferencia != null ?
                new ObjectParameter("folio_transferencia", folio_transferencia) :
                new ObjectParameter("folio_transferencia", typeof(string));
    
            var importeGeneralParameter = importeGeneral.HasValue ?
                new ObjectParameter("importeGeneral", importeGeneral) :
                new ObjectParameter("importeGeneral", typeof(decimal));
    
            var ivaGeneralParameter = ivaGeneral.HasValue ?
                new ObjectParameter("ivaGeneral", ivaGeneral) :
                new ObjectParameter("ivaGeneral", typeof(decimal));
    
            var iepsGeneralParameter = iepsGeneral.HasValue ?
                new ObjectParameter("iepsGeneral", iepsGeneral) :
                new ObjectParameter("iepsGeneral", typeof(decimal));
    
            var costoGeneralParameter = costoGeneral.HasValue ?
                new ObjectParameter("costoGeneral", costoGeneral) :
                new ObjectParameter("costoGeneral", typeof(decimal));
    
            var unidadesGeneralParameter = unidadesGeneral.HasValue ?
                new ObjectParameter("unidadesGeneral", unidadesGeneral) :
                new ObjectParameter("unidadesGeneral", typeof(decimal));
    
            var piezasGeneralParameter = piezasGeneral.HasValue ?
                new ObjectParameter("piezasGeneral", piezasGeneral) :
                new ObjectParameter("piezasGeneral", typeof(decimal));
    
            var pesoGeneralParameter = pesoGeneral.HasValue ?
                new ObjectParameter("pesoGeneral", pesoGeneral) :
                new ObjectParameter("pesoGeneral", typeof(decimal));
    
            var volumenGeneralParameter = volumenGeneral.HasValue ?
                new ObjectParameter("volumenGeneral", volumenGeneral) :
                new ObjectParameter("volumenGeneral", typeof(decimal));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var razon_aod_inventarioParameter = razon_aod_inventario != null ?
                new ObjectParameter("razon_aod_inventario", razon_aod_inventario) :
                new ObjectParameter("razon_aod_inventario", typeof(string));
    
            var folio_referenciaParameter = folio_referencia != null ?
                new ObjectParameter("folio_referencia", folio_referencia) :
                new ObjectParameter("folio_referencia", typeof(string));
    
            var orden_embarqueParameter = orden_embarque.HasValue ?
                new ObjectParameter("orden_embarque", orden_embarque) :
                new ObjectParameter("orden_embarque", typeof(short));
    
            var recoge_mercanciaParameter = recoge_mercancia.HasValue ?
                new ObjectParameter("recoge_mercancia", recoge_mercancia) :
                new ObjectParameter("recoge_mercancia", typeof(bool));
    
            var notasGeneralParameter = notasGeneral != null ?
                new ObjectParameter("notasGeneral", notasGeneral) :
                new ObjectParameter("notasGeneral", typeof(string));
    
            var clave_afectacion_inventarioParameter = clave_afectacion_inventario != null ?
                new ObjectParameter("clave_afectacion_inventario", clave_afectacion_inventario) :
                new ObjectParameter("clave_afectacion_inventario", typeof(string));
    
            var operacionParameter = operacion != null ?
                new ObjectParameter("Operacion", operacion) :
                new ObjectParameter("Operacion", typeof(string));
    
            var cod_cteParameter = cod_cte != null ?
                new ObjectParameter("cod_cte", cod_cte) :
                new ObjectParameter("cod_cte", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GuardarEntradaDevolucion", folioParameter, transaccionParameter, transaccion_origenParameter, cod_estabParameter, cod_estab_alternoParameter, folio_transferenciaParameter, importeGeneralParameter, ivaGeneralParameter, iepsGeneralParameter, costoGeneralParameter, unidadesGeneralParameter, piezasGeneralParameter, pesoGeneralParameter, volumenGeneralParameter, usuarioParameter, razon_aod_inventarioParameter, folio_referenciaParameter, orden_embarqueParameter, recoge_mercanciaParameter, notasGeneralParameter, clave_afectacion_inventarioParameter, operacionParameter, cod_cteParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_ConsultaPallet_Result> CalkinsWS_ConsultaPallet(string pallet, string localizacion, Nullable<bool> esPallet, string codEstab, Nullable<bool> traetPallet)
        {
            var palletParameter = pallet != null ?
                new ObjectParameter("Pallet", pallet) :
                new ObjectParameter("Pallet", typeof(string));
    
            var localizacionParameter = localizacion != null ?
                new ObjectParameter("Localizacion", localizacion) :
                new ObjectParameter("Localizacion", typeof(string));
    
            var esPalletParameter = esPallet.HasValue ?
                new ObjectParameter("EsPallet", esPallet) :
                new ObjectParameter("EsPallet", typeof(bool));
    
            var codEstabParameter = codEstab != null ?
                new ObjectParameter("CodEstab", codEstab) :
                new ObjectParameter("CodEstab", typeof(string));
    
            var traetPalletParameter = traetPallet.HasValue ?
                new ObjectParameter("TraetPallet", traetPallet) :
                new ObjectParameter("TraetPallet", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_ConsultaPallet_Result>("CalkinsWS_ConsultaPallet", palletParameter, localizacionParameter, esPalletParameter, codEstabParameter, traetPalletParameter);
        }
    
        public virtual int CalkinsWS_GuardarPallet(string pallet, string localizacion, Nullable<System.DateTime> fechaCad, string loteFab)
        {
            var palletParameter = pallet != null ?
                new ObjectParameter("Pallet", pallet) :
                new ObjectParameter("Pallet", typeof(string));
    
            var localizacionParameter = localizacion != null ?
                new ObjectParameter("Localizacion", localizacion) :
                new ObjectParameter("Localizacion", typeof(string));
    
            var fechaCadParameter = fechaCad.HasValue ?
                new ObjectParameter("FechaCad", fechaCad) :
                new ObjectParameter("FechaCad", typeof(System.DateTime));
    
            var loteFabParameter = loteFab != null ?
                new ObjectParameter("LoteFab", loteFab) :
                new ObjectParameter("LoteFab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_GuardarPallet", palletParameter, localizacionParameter, fechaCadParameter, loteFabParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_EntradasSalidasLoc_Result> CalkinsWS_EntradasSalidasLoc(string loc)
        {
            var locParameter = loc != null ?
                new ObjectParameter("Loc", loc) :
                new ObjectParameter("Loc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_EntradasSalidasLoc_Result>("CalkinsWS_EntradasSalidasLoc", locParameter);
        }
    
        public virtual int CalkinsWS_NuevoLote(string folio, string cod_estab, string cod_prod, Nullable<decimal> cantidad, string unidad, string abreviatura_unidad, string folio_referencia, string transaccion_referencia, Nullable<System.DateTime> fecha_caducidad, string lote_fabricacion, string localizacion, string loteRecep, ObjectParameter msg)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("Cod_estab", cod_estab) :
                new ObjectParameter("Cod_estab", typeof(string));
    
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("Cod_prod", cod_prod) :
                new ObjectParameter("Cod_prod", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("Cantidad", cantidad) :
                new ObjectParameter("Cantidad", typeof(decimal));
    
            var unidadParameter = unidad != null ?
                new ObjectParameter("Unidad", unidad) :
                new ObjectParameter("Unidad", typeof(string));
    
            var abreviatura_unidadParameter = abreviatura_unidad != null ?
                new ObjectParameter("Abreviatura_unidad", abreviatura_unidad) :
                new ObjectParameter("Abreviatura_unidad", typeof(string));
    
            var folio_referenciaParameter = folio_referencia != null ?
                new ObjectParameter("Folio_referencia", folio_referencia) :
                new ObjectParameter("Folio_referencia", typeof(string));
    
            var transaccion_referenciaParameter = transaccion_referencia != null ?
                new ObjectParameter("Transaccion_referencia", transaccion_referencia) :
                new ObjectParameter("Transaccion_referencia", typeof(string));
    
            var fecha_caducidadParameter = fecha_caducidad.HasValue ?
                new ObjectParameter("Fecha_caducidad", fecha_caducidad) :
                new ObjectParameter("Fecha_caducidad", typeof(System.DateTime));
    
            var lote_fabricacionParameter = lote_fabricacion != null ?
                new ObjectParameter("Lote_fabricacion", lote_fabricacion) :
                new ObjectParameter("Lote_fabricacion", typeof(string));
    
            var localizacionParameter = localizacion != null ?
                new ObjectParameter("Localizacion", localizacion) :
                new ObjectParameter("Localizacion", typeof(string));
    
            var loteRecepParameter = loteRecep != null ?
                new ObjectParameter("LoteRecep", loteRecep) :
                new ObjectParameter("LoteRecep", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_NuevoLote", folioParameter, cod_estabParameter, cod_prodParameter, cantidadParameter, unidadParameter, abreviatura_unidadParameter, folio_referenciaParameter, transaccion_referenciaParameter, fecha_caducidadParameter, lote_fabricacionParameter, localizacionParameter, loteRecepParameter, msg);
        }
    
        public virtual ObjectResult<CalkinsWS_RetirarMercanciaLoc_Result> CalkinsWS_RetirarMercanciaLoc(string loc)
        {
            var locParameter = loc != null ?
                new ObjectParameter("Loc", loc) :
                new ObjectParameter("Loc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_RetirarMercanciaLoc_Result>("CalkinsWS_RetirarMercanciaLoc", locParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_RetirarMercanciaProd_Result> CalkinsWS_RetirarMercanciaProd(string loc, string codProd)
        {
            var locParameter = loc != null ?
                new ObjectParameter("Loc", loc) :
                new ObjectParameter("Loc", typeof(string));
    
            var codProdParameter = codProd != null ?
                new ObjectParameter("CodProd", codProd) :
                new ObjectParameter("CodProd", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_RetirarMercanciaProd_Result>("CalkinsWS_RetirarMercanciaProd", locParameter, codProdParameter);
        }
    
        public virtual int CalkinsWS_ModificaInventarioLoc(string cod_prod, string unid, string localizacion, string lote, string cod_estab, Nullable<bool> afecta_no_disponible, ObjectParameter cant, Nullable<bool> guardar, Nullable<System.DateTime> fecha, string lote_Recepcion, string transaccion, string folio_referencia, string trans_referencia, string usuario)
        {
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var unidParameter = unid != null ?
                new ObjectParameter("unid", unid) :
                new ObjectParameter("unid", typeof(string));
    
            var localizacionParameter = localizacion != null ?
                new ObjectParameter("localizacion", localizacion) :
                new ObjectParameter("localizacion", typeof(string));
    
            var loteParameter = lote != null ?
                new ObjectParameter("lote", lote) :
                new ObjectParameter("lote", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var afecta_no_disponibleParameter = afecta_no_disponible.HasValue ?
                new ObjectParameter("afecta_no_disponible", afecta_no_disponible) :
                new ObjectParameter("afecta_no_disponible", typeof(bool));
    
            var guardarParameter = guardar.HasValue ?
                new ObjectParameter("guardar", guardar) :
                new ObjectParameter("guardar", typeof(bool));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var lote_RecepcionParameter = lote_Recepcion != null ?
                new ObjectParameter("lote_Recepcion", lote_Recepcion) :
                new ObjectParameter("lote_Recepcion", typeof(string));
    
            var transaccionParameter = transaccion != null ?
                new ObjectParameter("transaccion", transaccion) :
                new ObjectParameter("transaccion", typeof(string));
    
            var folio_referenciaParameter = folio_referencia != null ?
                new ObjectParameter("folio_referencia", folio_referencia) :
                new ObjectParameter("folio_referencia", typeof(string));
    
            var trans_referenciaParameter = trans_referencia != null ?
                new ObjectParameter("trans_referencia", trans_referencia) :
                new ObjectParameter("trans_referencia", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_ModificaInventarioLoc", cod_prodParameter, unidParameter, localizacionParameter, loteParameter, cod_estabParameter, afecta_no_disponibleParameter, cant, guardarParameter, fechaParameter, lote_RecepcionParameter, transaccionParameter, folio_referenciaParameter, trans_referenciaParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_ActualizarUbicacionLoc_Result> CalkinsWS_ActualizarUbicacionLoc(string loc)
        {
            var locParameter = loc != null ?
                new ObjectParameter("Loc", loc) :
                new ObjectParameter("Loc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_ActualizarUbicacionLoc_Result>("CalkinsWS_ActualizarUbicacionLoc", locParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_ActualizarUbicacionLote_Result> CalkinsWS_ActualizarUbicacionLote(string folio)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_ActualizarUbicacionLote_Result>("CalkinsWS_ActualizarUbicacionLote", folioParameter);
        }
    
        public virtual int CalkinsWS_ActualizarUbicacionGuardar(string loc, string cod_prodT, string loteT, string cod_prodR, string loteR, string usr, Nullable<bool> chkUbicar, string codEstab, Nullable<decimal> cant, string pallet)
        {
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var cod_prodTParameter = cod_prodT != null ?
                new ObjectParameter("cod_prodT", cod_prodT) :
                new ObjectParameter("cod_prodT", typeof(string));
    
            var loteTParameter = loteT != null ?
                new ObjectParameter("loteT", loteT) :
                new ObjectParameter("loteT", typeof(string));
    
            var cod_prodRParameter = cod_prodR != null ?
                new ObjectParameter("cod_prodR", cod_prodR) :
                new ObjectParameter("cod_prodR", typeof(string));
    
            var loteRParameter = loteR != null ?
                new ObjectParameter("loteR", loteR) :
                new ObjectParameter("loteR", typeof(string));
    
            var usrParameter = usr != null ?
                new ObjectParameter("usr", usr) :
                new ObjectParameter("usr", typeof(string));
    
            var chkUbicarParameter = chkUbicar.HasValue ?
                new ObjectParameter("ChkUbicar", chkUbicar) :
                new ObjectParameter("ChkUbicar", typeof(bool));
    
            var codEstabParameter = codEstab != null ?
                new ObjectParameter("CodEstab", codEstab) :
                new ObjectParameter("CodEstab", typeof(string));
    
            var cantParameter = cant.HasValue ?
                new ObjectParameter("Cant", cant) :
                new ObjectParameter("Cant", typeof(decimal));
    
            var palletParameter = pallet != null ?
                new ObjectParameter("Pallet", pallet) :
                new ObjectParameter("Pallet", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_ActualizarUbicacionGuardar", locParameter, cod_prodTParameter, loteTParameter, cod_prodRParameter, loteRParameter, usrParameter, chkUbicarParameter, codEstabParameter, cantParameter, palletParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_UbicarDocumento_Result> CalkinsWS_UbicarDocumento(string folio, string trans, string cod_estab, Nullable<bool> pallet, Nullable<bool> disponible, Nullable<int> indexDoc, Nullable<bool> picking, string tabla)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("trans", trans) :
                new ObjectParameter("trans", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var palletParameter = pallet.HasValue ?
                new ObjectParameter("Pallet", pallet) :
                new ObjectParameter("Pallet", typeof(bool));
    
            var disponibleParameter = disponible.HasValue ?
                new ObjectParameter("Disponible", disponible) :
                new ObjectParameter("Disponible", typeof(bool));
    
            var indexDocParameter = indexDoc.HasValue ?
                new ObjectParameter("IndexDoc", indexDoc) :
                new ObjectParameter("IndexDoc", typeof(int));
    
            var pickingParameter = picking.HasValue ?
                new ObjectParameter("Picking", picking) :
                new ObjectParameter("Picking", typeof(bool));
    
            var tablaParameter = tabla != null ?
                new ObjectParameter("Tabla", tabla) :
                new ObjectParameter("Tabla", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_UbicarDocumento_Result>("CalkinsWS_UbicarDocumento", folioParameter, transParameter, cod_estabParameter, palletParameter, disponibleParameter, indexDocParameter, pickingParameter, tablaParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_UbicarBusqueda_Result> CalkinsWS_UbicarBusqueda(string folio, string documento)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_UbicarBusqueda_Result>("CalkinsWS_UbicarBusqueda", folioParameter, documentoParameter);
        }
    
        public virtual int CalkinsWS_UbicarLocalizacion(string folio, string cod_prod, string cod_estab, Nullable<int> rack, Nullable<bool> disponible, Nullable<bool> pickslot)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var rackParameter = rack.HasValue ?
                new ObjectParameter("rack", rack) :
                new ObjectParameter("rack", typeof(int));
    
            var disponibleParameter = disponible.HasValue ?
                new ObjectParameter("disponible", disponible) :
                new ObjectParameter("disponible", typeof(bool));
    
            var pickslotParameter = pickslot.HasValue ?
                new ObjectParameter("pickslot", pickslot) :
                new ObjectParameter("pickslot", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_UbicarLocalizacion", folioParameter, cod_prodParameter, cod_estabParameter, rackParameter, disponibleParameter, pickslotParameter);
        }
    
        public virtual int CalkinsWS_UbicarGuardar(string folio, string loc, Nullable<bool> disponible, Nullable<bool> picking, string cod_estab, Nullable<bool> guardo)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("Loc", loc) :
                new ObjectParameter("Loc", typeof(string));
    
            var disponibleParameter = disponible.HasValue ?
                new ObjectParameter("disponible", disponible) :
                new ObjectParameter("disponible", typeof(bool));
    
            var pickingParameter = picking.HasValue ?
                new ObjectParameter("picking", picking) :
                new ObjectParameter("picking", typeof(bool));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var guardoParameter = guardo.HasValue ?
                new ObjectParameter("guardo", guardo) :
                new ObjectParameter("guardo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_UbicarGuardar", folioParameter, locParameter, disponibleParameter, pickingParameter, cod_estabParameter, guardoParameter);
        }
    
        public virtual int CalkinsWS_Ubicar_Guardar(string folio, string loc, Nullable<bool> disponible, Nullable<bool> picking, string cod_estab, ObjectParameter guardo)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var locParameter = loc != null ?
                new ObjectParameter("Loc", loc) :
                new ObjectParameter("Loc", typeof(string));
    
            var disponibleParameter = disponible.HasValue ?
                new ObjectParameter("disponible", disponible) :
                new ObjectParameter("disponible", typeof(bool));
    
            var pickingParameter = picking.HasValue ?
                new ObjectParameter("picking", picking) :
                new ObjectParameter("picking", typeof(bool));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_Ubicar_Guardar", folioParameter, locParameter, disponibleParameter, pickingParameter, cod_estabParameter, guardo);
        }
    
        public virtual ObjectResult<string> CalkinsWS_Ubicar_Localizacion(string folio, string cod_prod, string cod_estab, Nullable<int> rack, Nullable<bool> disponible, Nullable<bool> pickslot)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var rackParameter = rack.HasValue ?
                new ObjectParameter("rack", rack) :
                new ObjectParameter("rack", typeof(int));
    
            var disponibleParameter = disponible.HasValue ?
                new ObjectParameter("disponible", disponible) :
                new ObjectParameter("disponible", typeof(bool));
    
            var pickslotParameter = pickslot.HasValue ?
                new ObjectParameter("pickslot", pickslot) :
                new ObjectParameter("pickslot", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CalkinsWS_Ubicar_Localizacion", folioParameter, cod_prodParameter, cod_estabParameter, rackParameter, disponibleParameter, pickslotParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_Surtido_Result> CalkinsWS_Surtido(Nullable<int> index, string cod_estab, string folio_surtido)
        {
            var indexParameter = index.HasValue ?
                new ObjectParameter("index", index) :
                new ObjectParameter("index", typeof(int));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var folio_surtidoParameter = folio_surtido != null ?
                new ObjectParameter("folio_surtido", folio_surtido) :
                new ObjectParameter("folio_surtido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_Surtido_Result>("CalkinsWS_Surtido", indexParameter, cod_estabParameter, folio_surtidoParameter);
        }
    
        public virtual int CalkinsWS_SurtidoGuardar(string loc, string cod_prod, Nullable<int> ticket, string folioSurtido, Nullable<decimal> cant_surtida, string trans_surtido, string trans, string folio, string cod_estab, string usuario, string documento, ObjectParameter msg)
        {
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var ticketParameter = ticket.HasValue ?
                new ObjectParameter("ticket", ticket) :
                new ObjectParameter("ticket", typeof(int));
    
            var folioSurtidoParameter = folioSurtido != null ?
                new ObjectParameter("folioSurtido", folioSurtido) :
                new ObjectParameter("folioSurtido", typeof(string));
    
            var cant_surtidaParameter = cant_surtida.HasValue ?
                new ObjectParameter("cant_surtida", cant_surtida) :
                new ObjectParameter("cant_surtida", typeof(decimal));
    
            var trans_surtidoParameter = trans_surtido != null ?
                new ObjectParameter("trans_surtido", trans_surtido) :
                new ObjectParameter("trans_surtido", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("trans", trans) :
                new ObjectParameter("trans", typeof(string));
    
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var documentoParameter = documento != null ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_SurtidoGuardar", locParameter, cod_prodParameter, ticketParameter, folioSurtidoParameter, cant_surtidaParameter, trans_surtidoParameter, transParameter, folioParameter, cod_estabParameter, usuarioParameter, documentoParameter, msg);
        }
    
        public virtual ObjectResult<CalkinsWS_ReubicarProducto_Result> CalkinsWS_ReubicarProducto(string localizacion, string estab)
        {
            var localizacionParameter = localizacion != null ?
                new ObjectParameter("localizacion", localizacion) :
                new ObjectParameter("localizacion", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("estab", estab) :
                new ObjectParameter("estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_ReubicarProducto_Result>("CalkinsWS_ReubicarProducto", localizacionParameter, estabParameter);
        }
    
        public virtual ObjectResult<string> CalkinsWS_ReubicarLocDisponibles(string cod_prod, string cod_estab, Nullable<bool> montacargas)
        {
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var montacargasParameter = montacargas.HasValue ?
                new ObjectParameter("montacargas", montacargas) :
                new ObjectParameter("montacargas", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CalkinsWS_ReubicarLocDisponibles", cod_prodParameter, cod_estabParameter, montacargasParameter);
        }
    
        public virtual int CalkinsWS_ModificaNoDisponible(string cod_prod, string unidad, string trans, Nullable<decimal> cant, string cod_estab, ObjectParameter msg, string razonND, string usuario)
        {
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var unidadParameter = unidad != null ?
                new ObjectParameter("unidad", unidad) :
                new ObjectParameter("unidad", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("trans", trans) :
                new ObjectParameter("trans", typeof(string));
    
            var cantParameter = cant.HasValue ?
                new ObjectParameter("cant", cant) :
                new ObjectParameter("cant", typeof(decimal));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var razonNDParameter = razonND != null ?
                new ObjectParameter("razonND", razonND) :
                new ObjectParameter("razonND", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_ModificaNoDisponible", cod_prodParameter, unidadParameter, transParameter, cantParameter, cod_estabParameter, msg, razonNDParameter, usuarioParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_SurtidoPickingRefrescar_Result> CalkinsWS_SurtidoPickingRefrescar(string folio, string trans, string cod_estab, ObjectParameter msg)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("trans", trans) :
                new ObjectParameter("trans", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_SurtidoPickingRefrescar_Result>("CalkinsWS_SurtidoPickingRefrescar", folioParameter, transParameter, cod_estabParameter, msg);
        }
    
        public virtual ObjectResult<CalkinsWS_SurtidoPickingProdTicket_Result> CalkinsWS_SurtidoPickingProdTicket(string folio, string trans, string cod_estab, string ticket)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("trans", trans) :
                new ObjectParameter("trans", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            var ticketParameter = ticket != null ?
                new ObjectParameter("ticket", ticket) :
                new ObjectParameter("ticket", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_SurtidoPickingProdTicket_Result>("CalkinsWS_SurtidoPickingProdTicket", folioParameter, transParameter, cod_estabParameter, ticketParameter);
        }
    
        public virtual ObjectResult<string> CalkinsWS_LocProductoIntegracion(string cod_cte, string numdpc, string cod_prod, string cod_estab)
        {
            var cod_cteParameter = cod_cte != null ?
                new ObjectParameter("cod_cte", cod_cte) :
                new ObjectParameter("cod_cte", typeof(string));
    
            var numdpcParameter = numdpc != null ?
                new ObjectParameter("numdpc", numdpc) :
                new ObjectParameter("numdpc", typeof(string));
    
            var cod_prodParameter = cod_prod != null ?
                new ObjectParameter("cod_prod", cod_prod) :
                new ObjectParameter("cod_prod", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CalkinsWS_LocProductoIntegracion", cod_cteParameter, numdpcParameter, cod_prodParameter, cod_estabParameter);
        }
    
        public virtual int CalkinsWS_SurtidoPickingGuardar(string folio, string trans, string ticket, string codCte, string numdpc, string prod, string unid, string localizacion, Nullable<decimal> cant, string estab, string usuario, string contenedor, Nullable<int> tipoPick, ObjectParameter msg)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("Folio", folio) :
                new ObjectParameter("Folio", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("Trans", trans) :
                new ObjectParameter("Trans", typeof(string));
    
            var ticketParameter = ticket != null ?
                new ObjectParameter("Ticket", ticket) :
                new ObjectParameter("Ticket", typeof(string));
    
            var codCteParameter = codCte != null ?
                new ObjectParameter("CodCte", codCte) :
                new ObjectParameter("CodCte", typeof(string));
    
            var numdpcParameter = numdpc != null ?
                new ObjectParameter("Numdpc", numdpc) :
                new ObjectParameter("Numdpc", typeof(string));
    
            var prodParameter = prod != null ?
                new ObjectParameter("Prod", prod) :
                new ObjectParameter("Prod", typeof(string));
    
            var unidParameter = unid != null ?
                new ObjectParameter("Unid", unid) :
                new ObjectParameter("Unid", typeof(string));
    
            var localizacionParameter = localizacion != null ?
                new ObjectParameter("Localizacion", localizacion) :
                new ObjectParameter("Localizacion", typeof(string));
    
            var cantParameter = cant.HasValue ?
                new ObjectParameter("Cant", cant) :
                new ObjectParameter("Cant", typeof(decimal));
    
            var estabParameter = estab != null ?
                new ObjectParameter("Estab", estab) :
                new ObjectParameter("Estab", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var contenedorParameter = contenedor != null ?
                new ObjectParameter("Contenedor", contenedor) :
                new ObjectParameter("Contenedor", typeof(string));
    
            var tipoPickParameter = tipoPick.HasValue ?
                new ObjectParameter("TipoPick", tipoPick) :
                new ObjectParameter("TipoPick", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CalkinsWS_SurtidoPickingGuardar", folioParameter, transParameter, ticketParameter, codCteParameter, numdpcParameter, prodParameter, unidParameter, localizacionParameter, cantParameter, estabParameter, usuarioParameter, contenedorParameter, tipoPickParameter, msg);
        }
    
        public virtual ObjectResult<CalkinsWS_SurtidoPickingValidaLoc_Result> CalkinsWS_SurtidoPickingValidaLoc(string loc, string estab)
        {
            var locParameter = loc != null ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(string));
    
            var estabParameter = estab != null ?
                new ObjectParameter("estab", estab) :
                new ObjectParameter("estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_SurtidoPickingValidaLoc_Result>("CalkinsWS_SurtidoPickingValidaLoc", locParameter, estabParameter);
        }
    
        public virtual ObjectResult<CalkinsWS_SurtidoPicking_Refrescar_Result> CalkinsWS_SurtidoPicking_Refrescar(string folio, string trans, string cod_estab, ObjectParameter msg)
        {
            var folioParameter = folio != null ?
                new ObjectParameter("folio", folio) :
                new ObjectParameter("folio", typeof(string));
    
            var transParameter = trans != null ?
                new ObjectParameter("trans", trans) :
                new ObjectParameter("trans", typeof(string));
    
            var cod_estabParameter = cod_estab != null ?
                new ObjectParameter("cod_estab", cod_estab) :
                new ObjectParameter("cod_estab", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CalkinsWS_SurtidoPicking_Refrescar_Result>("CalkinsWS_SurtidoPicking_Refrescar", folioParameter, transParameter, cod_estabParameter, msg);
        }
    }
}
