//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_localizacion
    {
        public string localizacion { get; set; }
        public string cod_estab { get; set; }
        public string cod_prod { get; set; }
        public string lote { get; set; }
        public decimal exist_unidades { get; set; }
        public decimal exist_piezas { get; set; }
        public decimal unidades_no_disponibles { get; set; }
        public decimal piezas_no_disponibles { get; set; }
        public System.DateTime fecha { get; set; }
        public string lote_recepcion { get; set; }
    }
}
