//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario_localizacion
    {
        public string localizacion { get; set; }
        public string cod_estab { get; set; }
        public string cod_prod { get; set; }
        public string lote { get; set; }
        public decimal exist_unidades { get; set; }
        public decimal exist_piezas { get; set; }
        public decimal unidades_no_disponibles { get; set; }
        public decimal piezas_no_disponibles { get; set; }
        public System.DateTime fecha { get; set; }
        public string lote_recepcion { get; set; }
    }
}
