//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class localizacione
    {
        public string localizacion { get; set; }
        public string cod_estab { get; set; }
        public System.DateTime fecha { get; set; }
        public bool pick_slot { get; set; }
        public bool disponible { get; set; }
        public System.DateTime ultima_modificacion { get; set; }
        public string zona { get; set; }
        public string pasillo { get; set; }
        public string rack { get; set; }
        public string posicion { get; set; }
        public string profundidad { get; set; }
        public string nivel { get; set; }
        public string clasificador_producto { get; set; }
        public bool multiples_productos { get; set; }
        public bool mercancia_disponible { get; set; }
        public short minimo { get; set; }
        public short maximo { get; set; }
        public Nullable<int> orden_surtido { get; set; }
    }
}
