//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedore
    {
        public string cod_prv { get; set; }
        public string tipo_cuenta_pagar { get; set; }
        public string tipo_proveedor { get; set; }
        public string razon_social { get; set; }
        public string clasificacion_fiscal { get; set; }
        public string nombre { get; set; }
        public string ap_paterno { get; set; }
        public string ap_materno { get; set; }
        public string nom_comercial { get; set; }
        public string calle { get; set; }
        public string num_exterior { get; set; }
        public string num_interior { get; set; }
        public string colonia { get; set; }
        public string cod_postal { get; set; }
        public string delegacion { get; set; }
        public string pobmunedo { get; set; }
        public string tel1 { get; set; }
        public string tel2 { get; set; }
        public string fax { get; set; }
        public string rfc { get; set; }
        public string clave_iva { get; set; }
        public string flexibilidad_precio { get; set; }
        public bool productos_catalogados { get; set; }
        public string pago_flete { get; set; }
        public decimal reembolso_flete { get; set; }
        public decimal pedido_minimo { get; set; }
        public string tipo_minimo { get; set; }
        public string codigo_nuestro_proveedor { get; set; }
        public string manejo_devoluciones { get; set; }
        public short plazo { get; set; }
        public byte tolerancia_pago { get; set; }
        public bool abono_en_cuenta { get; set; }
        public bool retencion_pago { get; set; }
        public bool back_order { get; set; }
        public string autorizacion_ordenes_compra { get; set; }
        public string pagina_web { get; set; }
        public string moneda { get; set; }
        public System.DateTime fecha_alta { get; set; }
        public string pais { get; set; }
        public string estado { get; set; }
        public string municipio { get; set; }
        public string poblacion { get; set; }
        public string cod_estab { get; set; }
        public bool linea_fletera { get; set; }
        public string formato_factura { get; set; }
        public bool pago_estricto { get; set; }
        public string status_proveedor { get; set; }
        public string e_mail { get; set; }
        public System.DateTime ultima_modificacion { get; set; }
        public string proveedor_linea_fletera { get; set; }
        public string condicion_plazo { get; set; }
        public string giro_proveedor { get; set; }
        public string curp { get; set; }
        public string entre_calles { get; set; }
        public string orientacion { get; set; }
        public string mapa { get; set; }
        public short coordenada_x { get; set; }
        public short coordenada_y { get; set; }
        public string clave_valor_pagar { get; set; }
        public byte evaluacion_proveedor { get; set; }
        public string notas { get; set; }
        public bool iva_incluido_precio { get; set; }
        public string nacionalidad { get; set; }
        public bool comitente { get; set; }
        public string condicion_pago { get; set; }
        public string cod_cte { get; set; }
        public bool envio_directo_cliente { get; set; }
        public short te { get; set; }
        public string comprador { get; set; }
        public decimal limite_credito { get; set; }
        public byte tolerancia_limite_credito { get; set; }
        public bool paqueteria { get; set; }
        public bool afianzadora { get; set; }
        public bool aseguradora { get; set; }
        public string tipo_documento_venta { get; set; }
        public string usuario_ultima_modificacion { get; set; }
        public short dias_atencion_oc { get; set; }
        public bool exige_orden_compra_anticipos { get; set; }
        public string geolocalizacion { get; set; }
    }
}
