//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class razones_no_disponible
    {
        public string razon_nodisponible { get; set; }
        public string nombre { get; set; }
        public string abreviatura { get; set; }
        public string status { get; set; }
    }
}
