//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class razones_devoluciones_clientes
    {
        public string razon_devoluciones_clientes { get; set; }
        public string nombre { get; set; }
        public string abreviatura { get; set; }
        public string status { get; set; }
        public string causante_devoluciones_clientes { get; set; }
        public bool afecta_comision_ventas { get; set; }
        public byte cargo { get; set; }
        public string cod_prod_cargo { get; set; }
        public bool exige_notas { get; set; }
        public string razon_credito_clientes { get; set; }
    }
}
