//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSMobileWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes_surtido_pick_slot
    {
        public string folio { get; set; }
        public string cod_prod { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.DateTime> fecha_surtido { get; set; }
        public string usuario { get; set; }
        public string usuario_surtido { get; set; }
        public string status { get; set; }
        public string orden_carga { get; set; }
        public string localizacion { get; set; }
    }
}
